export * from './module'

export * from './auth'
export * from './bio-product'
export * from './branch'
export * from './diagnosis'
export * from './doctor'
export * from './instrument'
export * from './patient'
export * from './patient-type'
export * from './print-form'
export * from './role'
export * from './sample'
export * from './sample-type'
export * from './test'
export * from './test-category'
export * from './test-combo'
export * from './test-element'
export * from './user'

export * from './example-service'
