export enum ServiceErrorCode {
  BROWSER_UNKNOWN = 'BROWSER_UNKNOWN',
  BROWSER_PUPPETEER = 'BROWSER_PUPPETEER',
  BROWSER_PUPPETEER_INIT_FAILED = 'BROWSER_PUPPETEER_INIT_FAILED',
  BROWSER_VALIDATION = 'BROWSER_VALIDATION',
  BROWSER_VALIDATION_REQUEST_FAILED = 'BROWSER_VALIDATION_REQUEST_FAILED',
}
