apiVersion: 12
datasources:
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    orgId: 1
    url: http://loki-gateway.observability.svc.cluster.local
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
