export enum DomainErrorCode {
  UNKNOWN = 'UNKNOWN',

  AUTHN = 'AUTHN',
  AUTHN_JWT_INVALID_TOKEN = 'AUTHN_JWT_INVALID_TOKEN',
  AUTHN_LOGIN_INVALID_USERNAME = 'AUTHN_LOGIN_INVALID_USERNAME',
  AUTHN_LOGIN_INVALID_PASSWORD = 'AUTHN_LOGIN_INVALID_PASSWORD',
  AUTHN_COOKIE_ACCESS_TOKEN_NOT_FOUND = 'AUTHN_COOKIE_ACCESS_TOKEN_NOT_FOUND',
  AUTHN_PAYLOAD_NOT_FOUND = 'AUTHN_PAYLOAD_NOT_FOUND',
  AUTHN_PAYLOAD_USER_NOT_FOUND = 'AUTHN_PAYLOAD_USER_NOT_FOUND',

  AUTHZ = 'AUTHZ',
  AUTHZ_AUTHENTICATION_REQUIRED = 'AUTHZ_AUTHENTICATION_REQUIRED',
  AUTHZ_PERMISSION_DENIED = 'AUTHZ_PERMISSION_DENIED',

  ENTITY = 'ENTITY',
  ENTITY_NOT_FOUND = 'ENTITY_NOT_FOUND',

  SERVICE = 'SERVICE',
}
