apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.6.1
      helm:
        values: |
          helmPreUpgradeCheckerJob:
            enabled: false
          namespaceOverride: longhorn-system
          longhornUI:
            replicas: 1
          # metrics:
          #   serviceMonitor:
          #     enabled: true
          persistence:
            defaultClassReplicaCount: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
