argo-cd:
  fullnameOverride: argocd
  configs:
    params:
      server.insecure: true
  crds:
    keep: true
  notifications:
    enabled: false
  dex:
    enabled: false

prometheus-operator-crds:
  crds:
    annotations:
      argocd.argoproj.io/sync-options: Replace=true
