apiVersion: v2
name: core
description: A Helm chart for Kubernetes
type: application
version: 0.0.1

dependencies:
  - name: argo-cd
    repository: https://argoproj.github.io/argo-helm
    version: 6.7.10
