services:
  client:
    restart: unless-stopped
    build:
      context: ../../
      dockerfile: ./apps/levansy-web-app/Dockerfile
    env_file:
      - ../../apps/levansy-web-app/.env
    expose:
      - 80

  server:
    restart: unless-stopped
    build:
      context: ../../
      dockerfile: ./apps/levansy-access-service/Dockerfile
    expose:
      - 5000
      # - 8081
    networks:
      diut_infrastructure_network:

networks:
  diut_monitoring_network:
    external: true
  diut_infrastructure_network:
    external: true
