export enum COLLECTION {
  USER = 'users',
  PATIENT = 'patients',
  DOCTOR = 'doctors',
  TEST_CATEGORY = 'test_categories',
  TEST = 'tests',
  TEST_ELEMENT = 'test_elements',
  PATIENT_TYPE = 'patient_types',
  INDICATION = 'indications',
  SAMPLE = 'samples',
  TEST_RESULT = 'test_results',
  TEST_ELEMENT_RESULT = 'test_element_results',
  BIO_PRODUCT = 'bio_products',
  SAMPLE_TYPE = 'sample_types',
  TEST_COMBO = 'test_combos',
}
