export enum COLLECTION {
  USER = 'user',
  ROLE = 'role',
  PATIENT = 'patient',
  DOCTOR = 'doctor',
  TEST_CATEGORY = 'test_category',
  TEST = 'test',
  TEST_ELEMENT = 'test_element',
  PATIENT_TYPE = 'patient_type',
  DIAGNOSIS = 'diagnosis',
  SAMPLE = 'sample',
  BIO_PRODUCT = 'bio_product',
  INSTRUMENT = 'instrument',
  SAMPLE_TYPE = 'sample_type',
  TEST_COMBO = 'test_combo',
  PRINT_FORM = 'print_form',
  BRANCH = 'branch',
}
