export enum COLLECTION {
  USER = 'user',
  // PATIENT = 'patient',
  // DOCTOR = 'doctor',
  TEST_CATEGORY = 'test_category',
  // TEST = 'test',
  // TEST_ELEMENT = 'test_element',
  // PATIENT_TYPE = 'patient_type',
  // INDICATION = 'indication',
  // SAMPLE = 'sample',
  BIO_PRODUCT = 'bio_product',
  // SAMPLE_TYPE = 'sample_type',
  // TEST_COMBO = 'test_combo',
  // PRINT_FORM = 'print_form',
  // SAMPLE_ORIGIN = 'sample_origin',
  BRANCH = 'branch',
}
