apiVersion: v2
name: loki
description: A Helm chart for Kubernetes
type: application
version: 0.0.1

dependencies:
  - name: loki
    repository: https://grafana.github.io/helm-charts
    version: 6.1.0
