loki:
  loki:
    auth_enabled: false
    commonConfig:
      replication_factor: 2
    schemaConfig:
      configs:
        - from: 2024-04-01
          object_store: s3
          store: tsdb
          schema: v13
          index:
            prefix: index_
            period: 24h
    storage:
      bucketNames:
        chunks: loki-chunks
        ruler: loki-ruler
        admin: loki-admin
      type: s3
      s3:
        endpoint: http://minio.diut.svc.cluster.local:9000
        region: ap-southeast-1
        secretAccessKey: ${LOKI_MINIO_SECRET_KEY}
        accessKeyId: ${LOKI_MINIO_ACCESS_KEY}
        s3ForcePathStyle: true
        insecure: true
  test:
    enabled: false
  lokiCanary:
    enabled: false
  monitoring:
    rules:
      enabled: true
    serviceMonitor:
      enabled: true
    dashboards:
      enabled: true
  resultsCache:
    enabled: false
  chunksCache:
    enabled: false
  backend:
    replicas: 2
    extraArgs:
      - -config.expand-env=true
    extraEnvFrom:
      - secretRef:
          name: loki-credentials
  write:
    replicas: 2
    extraArgs:
      - -config.expand-env=true
    extraEnvFrom:
      - secretRef:
          name: loki-credentials
  read:
    replicas: 1
    extraArgs:
      - -config.expand-env=true
    extraEnvFrom:
      - secretRef:
          name: loki-credentials
  gateway:
    replicas: 1
    service:
      labels:
        prometheus.io/service-monitor: 'false'
    extraArgs:
      - -config.expand-env=true
    extraEnvFrom:
      - secretRef:
          name: loki-credentials
