apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hcdc-access-service
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: hcdc
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/hcdc-access-service/k8s/helm-chart
    repoURL: https://github.com/wermarter/diut
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
