apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-datasource
  namespace: observability
  labels:
    grafana_datasource: '1'
data:
  'datasource.yaml': |
    {{ $.Files.Get "src/datasource.yaml" | nindent 4 }}
