name: diut_levansy_local

services:
  client:
    build:
      target: development
    restart: 'no'
    volumes:
      - ../../apps/levansy-web-app/package.json:/usr/src/app/apps/levansy-web-app/package.json
      - ../../apps/levansy-web-app/src:/usr/src/app/apps/levansy-web-app/src
      - ../../libs/common/package.json:/usr/src/app/libs/common/package.json
      - ../../libs/common/src:/usr/src/app/libs/common/src
      - ../../libs/levansy-common/package.json:/usr/src/app/libs/levansy-common/package.json
      - ../../libs/levansy-common/src:/usr/src/app/libs/levansy-common/src
    ports:
      - '5173:5173'

  server:
    build:
      target: development
    restart: 'no'
    ports:
      - '5000:5000'
      # - '8081:8081'
    env_file:
      - ../../apps/levansy-access-service/.env.local
    volumes:
      - ../../apps/levansy-access-service/package.json:/usr/src/app/apps/levansy-access-service/package.json
      - ../../apps/levansy-access-service/src:/usr/src/app/apps/levansy-access-service/src
      - ../../libs/common/package.json:/usr/src/app/libs/common/package.json
      - ../../libs/common/src:/usr/src/app/libs/common/src
      - ../../libs/server-core/package.json:/usr/src/app/libs/server-core/package.json
      - ../../libs/server-core/src:/usr/src/app/libs/server-core/src
      - ../../libs/levansy-common/package.json:/usr/src/app/libs/levansy-common/package.json
      - ../../libs/levansy-common/src:/usr/src/app/libs/levansy-common/src
    networks:
      diut_monitoring_network:
        aliases:
          - levansy_access_service_local
