apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: core
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: diut
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s/dependencies/5-mongodb
    repoURL: https://github.com/wermarter/diut
    targetRevision: develop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true