mongodb:
  fullnameOverride: mongodb
  auth:
    rootUser: root
    existingSecret: mongodb-credentials

  architecture: replicaset
  replicaCount: 3
  arbiter:
    enabled: false
  volumePermissions:
    enabled: true

  metrics:
    enabled: true
    # compatibleMode: false
    serviceMonitor:
      enabled: true
      namespace: observability
    prometheusRule:
      enabled: true
      namespace: observability
