name: update Helm appVersion

on:
  push:
    branches:
      - develop # main

jobs:
  increment-version:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set foobar to cool
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.appVersion = "${{ github.run_number }}"' './apps/bathanghai-server/k8s/helm-chart/Chart.yaml'

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: update Helm appVersion'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
