name: diut_bathanghai_staging

services:
  client:
    ports:
      - '8082:80'

  server:
    ports:
      - '5002:5000'
    environment:
      OTEL_SERVICE_NAME: bathanghai_server_staging
    networks:
      diut_monitoring_network:
        aliases:
          - bathanghai_server_staging
