apiVersion: v2
name: crd
description: A Helm chart for Kubernetes
type: application
version: 0.0.1

dependencies:
  - name: prometheus-operator-crds
    repository: https://prometheus-community.github.io/helm-charts
    version: 17.0.2
