kind: EnvoyProxy
apiVersion: gateway.envoyproxy.io/v1alpha1
metadata:
  namespace: envoy-gateway-system
  name: external-proxy-config
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        name: gateway-external
        annotations:
          metallb.universe.tf/loadBalancerIPs: {{ .Values.loadBalancerIP }}
      envoyDaemonSet:
        name: gateway-external
  telemetry:
    tracing:
      samplingRate: 100
      provider:
        type: OpenTelemetry
        host: tempo-distributor.observability.svc.cluster.local
        port: 4317
      customTags:
        forwarded.request.ip:
          type: RequestHeader
          requestHeader:
            name: X-Forwarded-For
            defaultValue: "-"
---
kind: GatewayClass
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: gateway-external
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: external-proxy-config
    namespace: envoy-gateway-system
---
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: gateway-external
  namespace: envoy-gateway-system
spec:
  gatewayClassName: gateway-external
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
