apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: lowa
spec:
  mode: daemonset
  hostNetwork: true
  securityContext:
    privileged: true
    runAsUser: 0
  volumes:
    - name: logs
      hostPath:
        path: /var/log/pods
        type: Directory
  volumeMounts:
    - name: logs
      mountPath: /var/log/pods

  config:
    receivers:
      filelog:
        include_file_path: true
        include:
          - /var/log/pods/*/*/*.log
        operators:
          - id: container-parser
            type: container
    processors:
      batch:
        send_batch_size: 10000
        timeout: 10s
      k8sattributes:
        auth_type: 'serviceAccount'
        extract:
          metadata: # extracted from the pod
            - k8s.namespace.name
            - k8s.pod.name
            - k8s.pod.start_time
            - k8s.pod.uid
            - k8s.deployment.name
            - k8s.node.name
        pod_association: # How to associate the data to a pod (order matters)
          - sources: # First try to use the value of the resource attribute k8s.pod.ip
              - from: resource_attribute
                name: k8s.pod.ip
          - sources: # Then try to use the value of the resource attribute k8s.pod.uid
              - from: resource_attribute
                name: k8s.pod.uid
          - sources: # If neither of those work, use the request's connection to get the pod IP.
              - from: connection
    exporters:
      otlphttp:
        endpoint: http://loki-gateway.observability.svc.cluster.local/otlp
    service:
      pipelines:
        logs:
          receivers:
            - filelog
          processors:
            - k8sattributes
            - batch
          exporters:
            - otlphttp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lowa-collector
rules:
  - apiGroups:
      - ''
    resources:
      - 'pods'
      - 'namespaces'
    verbs:
      - 'get'
      - 'watch'
      - 'list'
  - apiGroups:
      - 'apps'
    resources:
      - 'replicasets'
    verbs:
      - 'get'
      - 'list'
      - 'watch'
  - apiGroups:
      - 'extensions'
    resources:
      - 'replicasets'
    verbs:
      - 'get'
      - 'list'
      - 'watch'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lowa-collector
subjects:
  - kind: ServiceAccount
    name: lowa-collector
    namespace: observability
roleRef:
  kind: ClusterRole
  name: lowa-collector
  apiGroup: rbac.authorization.k8s.io
