mongodb:
  fullnameOverride: diut-mongodb
  auth:
    rootUser: root
    existingSecret: mongodb-credentials

  architecture: replicaset
  replicaCount: 3
  arbiter:
    enabled: false

  externalAccess:
    enabled: true
    service:
      type: ClusterIP

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: observability
    prometheusRule:
      enabled: true
      namespace: observability
