redis:
  fullnameOverride: redis
  auth:
    enabled: false
  master:
    disableCommands: []
    resourcesPreset: 'large'
    persistence:
      storageClass:
      size: 5Gi
  replica:
    replicaCount: 1
    resourcesPreset: 'large'
    autoscaling:
      enabled: true
      maxReplicas: 3
      targetCPU: 80
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
    prometheusRule:
      enabled: true
  sysctl:
    enabled: true
    mountHostSys: true
    command:
      - /bin/sh
      - -c
      - |-
        install_packages procps
        sysctl -w net.core.somaxconn=10000
        echo never > /host-sys/kernel/mm/transparent_hugepage/enabled
