redis:
  fullnameOverride: redis
  auth:
    enabled: false
    sentinel: false
  sentinel:
    enabled: true
  master:
    disableCommands: []
    resourcesPreset: 'medium'
    persistence:
      storageClass: longhorn
      size: 5Gi
  replica:
    disableCommands: []
    replicaCount: 3
    persistence:
      storageClass: longhorn
      size: 5Gi
    resourcesPreset: 'medium'
    autoscaling:
      enabled: false
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
    prometheusRule:
      enabled: true
  sysctl:
    enabled: true
    mountHostSys: true
    command:
      - /bin/sh
      - -c
      - |-
        install_packages procps
        sysctl -w net.core.somaxconn=10000
        echo never > /host-sys/kernel/mm/transparent_hugepage/enabled
