apiVersion: v2
name: envoy-gateway
description: A Helm chart for Kubernetes
type: application
version: 0.0.1

dependencies:
  - name: gateway-helm
    repository: oci://docker.io/envoyproxy
    version: 1.2.4
