name: diut_infrastructure

services:
  mongo:
    restart: unless-stopped
    image: mongodb/mongodb-community-server:6.0.8-ubi8
    volumes:
      - mongo_data:/data/db
    ports:
      - '27017:27017'
    networks:
      - network

  minio:
    restart: unless-stopped
    image: minio/minio:RELEASE.2023-07-21T21-12-44Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_PROMETHEUS_AUTH_TYPE: public
      MINIO_PROMETHEUS_URL: http://prometheus:9090
      MINIO_PROMETHEUS_JOB_ID: minio
    volumes:
      - minio_data:/data
    expose:
      - 9000
      - 9001
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - network
      - diut_monitoring_network

volumes:
  mongo_data:
  minio_data:

networks:
  network:
  diut_monitoring_network:
    external: true
