longhorn:
  preUpgradeChecker:
    jobEnabled: false
  longhornUI:
    replicas: 2
  service:
    ui:
      type: 'LoadBalancer'
      loadBalancerIP: '10.1.1.203'
  persistence:
    defaultClassReplicaCount: 3
  csi:
    attacherReplicaCount: 2
    provisionerReplicaCount: 2
    resizerReplicaCount: 2
    snapshotterReplicaCount: 2
  defaultSettings:
    backupTarget: s3://diut-lab@ap-southeast-1/longhorn-backup
    backupTargetCredentialSecret: longhorn-backup-secret
