longhorn:
  preUpgradeChecker:
    jobEnabled: false
  longhornUI:
    replicas: 2
  persistence:
    defaultClassReplicaCount: 1
    defaultDataLocality: best-effort
  csi:
    attacherReplicaCount: 2
    provisionerReplicaCount: 2
    resizerReplicaCount: 2
    snapshotterReplicaCount: 2
  defaultSettings:
    autoDeletePodWhenVolumeDetachedUnexpectedly: true
