loki:
  loki:
    auth_enabled: false
    commonConfig:
      replication_factor: 1
    compactor:
      retention_enabled: true
      delete_request_store: s3
    limits_config:
      retention_period: 30d
      max_query_lookback: 30d
      max_query_series: 100000
      allow_structured_metadata: true
      discover_log_levels: true
      discover_service_name:
        - k8s_deployment_name
        - k8s_daemonset_name
        - k8s_statefulset_name
        - k8s_cronjob_name
        - k8s_job_name
      otlp_config:
        scope_attributes: []
        log_attributes: []
        resource_attributes:
          ignore_defaults: true
          attributes_config:
            - action: index_label
              attributes:
                - k8s.namespace.name
            - action: index_label
              attributes:
                - k8s.deployment.name
            - action: index_label
              attributes:
                - k8s.daemonset.name
            - action: index_label
              attributes:
                - k8s.statefulset.name
            - action: index_label
              attributes:
                - k8s.cronjob.name
            - action: index_label
              attributes:
                - k8s.job.name
            - action: structured_metadata
              attributes:
                - k8s.pod.uid
            - action: structured_metadata
              attributes:
                - k8s.pod.name
            - action: structured_metadata
              attributes:
                - k8s.container.name
            - action: structured_metadata
              attributes:
                - k8s.container.restart_count
    schemaConfig:
      configs:
        - from: 2024-04-01
          object_store: s3
          store: tsdb
          schema: v13
          index:
            prefix: index_
            period: 24h
    storage:
      bucketNames:
        chunks: loki-chunks
        ruler: loki-ruler
        admin: loki-admin
      type: s3
      s3:
        endpoint: http://minio.diut.svc.cluster.local:9000
        region: ap-southeast-1
        secretAccessKey: ${LOKI_MINIO_SECRET_KEY}
        accessKeyId: ${LOKI_MINIO_ACCESS_KEY}
        s3ForcePathStyle: true
        insecure: true
  test:
    enabled: false
  lokiCanary:
    enabled: false
  monitoring:
    rules:
      enabled: true
    serviceMonitor:
      enabled: true
    dashboards:
      enabled: true
  resultsCache:
    enabled: false
  chunksCache:
    enabled: false
  backend:
    replicas: 1
    persistence:
      size: 1Gi
    extraArgs:
      - -config.expand-env=true
    extraEnvFrom:
      - secretRef:
          name: loki-credentials
  write:
    replicas: 2
    persistence:
      size: 1Gi
    extraArgs:
      - -config.expand-env=true
    extraEnvFrom:
      - secretRef:
          name: loki-credentials
  read:
    replicas: 2
    persistence:
      size: 1Gi
    extraArgs:
      - -config.expand-env=true
    extraEnvFrom:
      - secretRef:
          name: loki-credentials
  gateway:
    replicas: 1
    service:
      labels:
        prometheus.io/service-monitor: 'false'
    extraArgs:
      - -config.expand-env=true
    extraEnvFrom:
      - secretRef:
          name: loki-credentials
