loki:
  loki:
    auth_enabled: false
    commonConfig:
      # set to 1, otherwise more replicas are needed to connect to grafana
      replication_factor: 1
    storage:
      bucketNames:
        chunks: loki-chunks
        ruler: loki-ruler
        admin: loki-admin
      type: s3
      s3:
        endpoint: http://minio.diut.svc.cluster.local:9000
        region: ap-southeast-1
        secretAccessKey: ${LOKI_MINIO_SECRET_KEY}
        accessKeyId: ${LOKI_MINIO_ACCESS_KEY}
        s3ForcePathStyle: true
        insecure: true
  test:
    enabled: false
  monitoring:
    lokiCanary:
      enabled: false
    selfMonitoring:
      enabled: false
      grafanaAgent:
        installOperator: false
  backend:
    replicas: 1
    extraArgs:
      - -config.expand-env=true
    extraEnvFrom:
      - secretRef:
          name: loki-credentials
  write:
    replicas: 1
    extraArgs:
      - -config.expand-env=true
    extraEnvFrom:
      - secretRef:
          name: loki-credentials
  read:
    replicas: 1
    extraArgs:
      - -config.expand-env=true
    extraEnvFrom:
      - secretRef:
          name: loki-credentials
  gateway:
    replicas: 1
    extraArgs:
      - -config.expand-env=true
    extraEnvFrom:
      - secretRef:
          name: loki-credentials
