export * from './base-entity'

export * from './bio-product'
export * from './diagnosis'
export * from './patient-type'
export * from './doctor'
export * from './instrument'
export * from './sample-type'
export * from './test-category'
export * from './role'
export * from './user'
export * from './branch'
export * from './permission-rule'
export * from './print-form'
export * from './test'
