name: diut_bathanghai_production

services:
  client:
    ports:
      - '8081:80'

  server:
    # labels:
    #   logging: 'promtail'
    #   logging_jobname: 'bathanghai_production_server'
    ports:
      - '5001:5000'
    environment:
      SERVICE_NAME: bathanghai_server_production
    networks:
      diut_monitoring_network:
        aliases:
          - bathanghai_server_production
