apiVersion: v2
name: kafka
description: A Helm chart for Kubernetes
type: application
version: 0.0.1

dependencies:
  - name: kafka
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 28.2.1
  - name: kafbat-ui
    repository: https://ui.charts.kafbat.io
    version: 1.4.0
