apiVersion: v2
name: mongodb
description: A Helm chart for mongodb
type: application
version: 0.0.1

dependencies:
  - name: mongodb
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 14.0.12
