minio:
  mode: distributed
  auth:
    existingSecret: minio-credentials
  metrics:
    serviceMonitor:
      enabled: true
      jobLabel: minio
      namespace: observability
      paths:
        - /minio/v2/metrics/cluster
        - /minio/v2/metrics/node
        - /minio/v2/metrics/bucket
    prometheusRule:
      enabled: true
      namespace: observability
  resourcesPreset: 'none'
  persistence:
    size: 60Gi
    storageClass: longhorn
  extraEnvVars:
    - name: MINIO_PROMETHEUS_URL
      value: http://prometheus-stack-prometheus.observability.svc.cluster.local:9090
    - name: MINIO_PROMETHEUS_JOB_ID
      value: minio
  provisioning:
    enabled: true
    buckets:
      - name: loki-chunks
      - name: loki-ruler
      - name: loki-admin
