minio:
  auth:
    existingSecret: minio-credentials
  metrics:
    serviceMonitor:
      enabled: true
      jobLabel: minio
      namespace: observability
    prometheusRule:
      enabled: true
      namespace: observability
  resourcesPreset: 'large'
  persistence:
    size: 20Gi
    storageClass: longhorn
  extraEnvVars:
    - name: MINIO_PROMETHEUS_URL
      value: http://prometheus-stack-prometheus.observability.svc.cluster.local:9090
    - name: MINIO_PROMETHEUS_JOB_ID
      value: minio
  defaultBuckets: 'loki-chunks, loki-ruler, loki-admin'
