name: diut_bathanghai_local

services:
  client:
    build:
      target: development
    restart: 'no'
    volumes:
      - ../../apps/web-app/package.json:/usr/src/app/apps/web-app/package.json
      - ../../apps/web-app/src:/usr/src/app/apps/web-app/src
      - ../../libs/common/package.json:/usr/src/app/libs/common/package.json
      - ../../libs/common/src:/usr/src/app/libs/common/src
    ports:
      - '5173:5173'

  server:
    # labels:
    #   logging: 'promtail'
    #   logging_jobname: 'bathanghai_server_local'
    build:
      target: development
    restart: 'no'
    ports:
      - '5000:5000'
      - '8081:8081'
    environment:
      OTEL_LOG_LEVEL: all
    env_file:
      - ../../apps/bathanghai-server/.env.local
    volumes:
      - ../../apps/bathanghai-server/package.json:/usr/src/app/apps/bathanghai-server/package.json
      - ../../apps/bathanghai-server/src:/usr/src/app/apps/bathanghai-server/src
      - ../../libs/common/package.json:/usr/src/app/libs/common/package.json
      - ../../libs/common/src:/usr/src/app/libs/common/src
    networks:
      diut_monitoring_network:
        aliases:
          - bathanghai_server_local
