export enum DomainErrorCode {
  UNKNOWN = 'UNKNOWN',

  AUTHN = 'AUTHN',
  AUTHN_INVALID_JWT_TOKEN = 'AUTHN_INVALID_JWT_TOKEN',
  AUTHN_LOGIN_INVALID_USERNAME = 'AUTHN_LOGIN_INVALID_USERNAME',
  AUTHN_LOGIN_INVALID_PASSWORD = 'AUTHN_LOGIN_INVALID_PASSWORD',

  AUTHZ = 'AUTHZ',
  AUTHZ_PAYLOAD_NOT_FOUND = 'AUTHZ_PAYLOAD_NOT_FOUND',
  AUTHZ_USER_NOT_FOUND = 'AUTHZ_USER_NOT_FOUND',

  ENTITY = 'ENTITY',

  SERVICE = 'SERVICE',
}
