export enum DomainErrorCode {
  UNKNOWN = 'UNKNOWN',

  AUTHN = 'AUTHN',
  AUTHN_PAYLOAD_NOT_FOUND = 'AUTHN_PAYLOAD_NOT_FOUND',
  AUTHN_INVALID_JWT_TOKEN = 'AUTHN_INVALID_JWT_TOKEN',

  AUTHZ = 'AUTHZ',

  ENTITY = 'ENTITY',

  SERVICE = 'SERVICE',
}
