- name: Longhorn requirement
  hosts: all
  become: true
  tasks:
    - name: Ensure nfs-common are installed
      ansible.builtin.package:
        name: nfs-common
        state: present

    - name: Append blacklist block to /etc/multipath.conf
      blockinfile:
        path: /etc/multipath.conf
        block: |
          blacklist {
              devnode "^sd[a-z0-9]+"
          }
        state: present
        insertafter: EOF

    - name: Restart the multipathd service
      service:
        name: multipathd
        state: restarted
