apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-operator
  namespace: core
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s/dependencies/11-otel
    repoURL: https://github.com/wermarter/diut
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
