apiVersion: v2
name: otel-collector
description: A Helm chart for Kubernetes
type: application
version: 0.0.1

dependencies:
  - name: opentelemetry-operator
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    version: 0.75.1
