mongodb:
  fullnameOverride: mongodb
  auth:
    rootUser: root
    existingSecret: mongodb-credentials

  architecture: replicaset
  replicaCount: 3
  arbiter:
    enabled: false

  # replicaSetHostnames: false
  # externalAccess:
  #   enabled: true
  #   service:
  #     type: ClusterIP

  # replicaSetConfigurationSettings:
  #   enabled: true
  #   configuration:
  #     members:
  #       - _id: 0
  #         host: mongodb-0.diut.svc.cluster.local
  #       - _id: 1
  #         host: mongodb-1.diut.svc.cluster.local
  #       - _id: 2
  #         host: mongodb-2.diut.svc.cluster.local

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: observability
    prometheusRule:
      enabled: true
      namespace: observability
