apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: browser-service
  namespace: infra
spec:
  parentRefs:
    - kind: Gateway
      name: gateway-internal
      namespace: envoy-gateway-system
      sectionName: grpc
  rules:
    - backendRefs:
        - name: browser-service
          port: 50051
      matches:
        - method:
            service: diut.BrowserService
            method: PrintMultiplePage
        - method:
            service: diut.BrowserService
            method: TestTimeout
        - method:
            service: diut.BrowserService
            method: TestError
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: browser-service-policy
  namespace: infra
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: GRPCRoute
      name: browser-service
  loadBalancer:
    type: RoundRobin
  timeout:
    http:
      requestTimeout: "60s"