apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: browser-service
  namespace: infra
spec:
  parentRefs:
    - kind: Gateway
      name: gateway-external
      namespace: envoy-gateway-system
      sectionName: http
  rules:
    - timeouts:
        request: "60s"
        backendRequest: "60s"
      matches:
        - path:
            type: PathPrefix
            value: /api
      backendRefs:
        - name: browser-service
          port: 5001
