name: Increment Helm Chart Version

on:
  push:
    branches:
      - develop

jobs:
  increment-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.13.0'

      - name: Set foobar to cool
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.appVersion = "${{ github.run_number }}"' './apps/bathanghai-server/k8s/helm-chart/Chart.yaml'

      # - name: Commit code
      #   run: |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     git add ./apps/bathanghai-server/k8s/helm-chart/Chart.yaml
      #     git commit -m "Increment Helm Chart Version" -m "[skip ci]"

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Increment Helm Chart Version

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
