name: deploy-production

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-web-app:
    name: Build web-app
    runs-on: ubuntu-22.04

    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Build project
        working-directory: ./apps/web-app
        run: yarn build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: web-app-dist
          path: ./apps/web-app/dist/
          if-no-files-found: error

  deploy-web-app:
    name: Deploy web-app
    needs: build-web-app
    runs-on: ubuntu-22.04
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: web-app-dist
          path: ./build

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'delegate to the next step'
      - name: Add known hosts
        run: ssh-keyscan -H -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: rsync -avz --rsync-path="echo ${{ secrets.SSH_SUDO_PASSWORD }} | sudo -Sv && sudo rsync" -e "ssh -p ${{ secrets.SSH_PORT }}" ./build/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/web-app
