name: Deploy access server

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - apps/access-server/**

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04

    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./access-server.dockerfile
          push: true
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/diut-bathanghai-production:latest
          cache-to: type=inline
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/diut-bathanghai-production:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/diut-bathanghai-production:${{ github.run_number }}

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'delegate to the next step'

      - name: Add known hosts
        run: ssh-keyscan -H -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Docker pull new image
        run: ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker pull ${{ secrets.DOCKERHUB_USERNAME }}/diut-bathanghai-production:latest"

      - name: Docker stop running container
        run: ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker rm $(docker stop $(docker ps -a -q --filter ancestor=${{ secrets.DOCKERHUB_USERNAME }}/diut-bathanghai-production --format="{{.ID}}")) || true"

      - name: Docker start new container
        run: ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker run --env-file=/var/www/diut-bathanghai-production.env -d --network=host ${{ secrets.DOCKERHUB_USERNAME }}/diut-bathanghai-production:latest"
