name: deploy-production

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-web-app:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./apps/web-app

    steps:
      - name: Get code
        uses: actions/checkout@v3

      # - name: Install dependencies
      #   run: yarn install --frozen-lockfile

      - name: Build project
        run: mkdir dist && echo "Building project hardworkingly..." >> dist/bundle3.txt

      - name: test files
        run: ls -al

      - name: test result
        run: ls -al dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: web-app-dist
          path: ./dist/

  deploy-web-app:
    needs: build-web-app
    runs-on: ubuntu-22.04
    steps:
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: web-app-dist
          path: ./build

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'delegate to the next step'
      - name: Add known hosts
        run: ssh-keyscan -H -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: rsync -avz -e "ssh -p ${{ secrets.SSH_PORT }}" ./build/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/test-gh-action
