name: levansy-access-service

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'libs/common/**'
      - 'libs/server-core/**'
      - 'libs/levansy-common/**'
      - 'apps/levansy-access-service/**'

jobs:
  j1:
    uses: ./.github/workflows/docker-publish.yaml
    with:
      dockerfile-path: ./apps/levansy-access-service/Dockerfile
      docker-image-name: diut-levansy-access-service
    secrets: inherit

  j2:
    needs: j1
    uses: ./.github/workflows/helm-appversion.yaml
    with:
      chart-path: ./apps/levansy-access-service/k8s/helm-chart/Chart.yaml
      identity: levansy-access-service
    secrets: inherit
