name: puppeteer-service

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'libs/common/**'
      - 'libs/nestjs-infra/**'
      - 'apps/puppeteer-service/**'

jobs:
  j1:
    uses: ./.github/workflows/docker-publish.yaml
    with:
      dockerfile-path: ./apps/puppeteer-service/Dockerfile
      docker-image-name: diut-puppeteer-service
    secrets: inherit

  j2:
    needs: j1
    uses: ./.github/workflows/helm-appversion.yaml
    with:
      chart-path: ./apps/puppeteer-service/k8s/helm-chart/Chart.yaml
      identity: puppeteer-service
    secrets: inherit
